import { useRouter } from 'next/router';
import Layout from '../../layout'
import { useFireproof } from 'use-fireproof';
import asciidoctor from 'asciidoctor';

export default function SectionPage() {
  const router = useRouter();
  const { id } = router.query;

  const { useDocument } = useFireproof('chagpt-hacks', () => {}, () => {}, {
    secondary: { type: 'rest', url: 'http://localhost:8000/chagpt-hacks' }
  });
  // @ts-ignore
  const [doc] = useDocument({_id : id});

  // Initialize asciidoctor.js
  const asciidoctorInstance = asciidoctor();

  // Convert doc.content to HTML
  const htmlContent = asciidoctorInstance.convert(doc?.content || '');

  const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
  }

  console.log('dc', id, doc)

  return (
    <Layout>
      <div className="px-4 prose dark:prose-invert" dangerouslySetInnerHTML={{__html: htmlContent}} />
    </Layout>
  );
}
