import { useRouter } from 'next/router'
import Layout from '../../layout'
import { useFireproof } from 'use-fireproof'
import asciidoctor from 'asciidoctor'
import { useEffect, useState } from 'react'

export default function SectionPage() {
  const router = useRouter()
  const { id } = router.query

  const { database } = useFireproof(
    'chagpt-hacks',
    () => {},
    () => {},
    {
      secondary: { type: 'rest', url: 'http://localhost:8000/chagpt-hacks' }
    }
  )
  // @ts-ignore
  // const [xdoc] = useDocument({_id : id});

  const [doc, setDoc] = useState({ content: '' })

  useEffect(() => {
    // console.log('id', id)
    const updateDoc = async () => {
      // @ts-ignore
      const doc = await database.get(id).catch({ content: '' })
      // @ts-ignore
      setDoc(doc)
    }
    updateDoc()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id])

  // Initialize asciidoctor.js
  const asciidoctorInstance = asciidoctor()

  // Convert doc.content to HTML
  const htmlContent = asciidoctorInstance.convert(doc?.content || '')

  const metadata = {
    title: doc.title,
    description: 'Generated by create app'
  }

  // console.log('dc', id, doc)

  return (
    <Layout>
      <div className="px-4 prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: htmlContent }} />
    </Layout>
  )
}
