import { useRouter } from 'next/router';
import Layout from '../../layout'

export default function SectionPage() {
  const router = useRouter();
  const { id } = router.query;

  const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
  }

  // Fetch passage data based on id

  return (
    <Layout>
      { id }
    </Layout>
  );
}
